name: Extract zip file

on:
  push:
    paths:
      - '**.zip'  # این قانون می‌گوید: هر بار که فایل زیپی به ریپو اضافه شد، این اکشن اجرا شود.
  workflow_dispatch: # این قانون هم اجازه می‌دهد به صورت دستی اجرایش کنی.

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          # پیدا کردن فایل زیپ در ریپازیتوری (فرض می‌کنیم فقط یک فایل هست)
          zip_file=$(find . -name "*.zip" -type f)
          echo "ZIP file found: $zip_file"

          # آنزیپ کردن فایل در همان پوشه
          unzip -o "$zip_file" -d "$(dirname "$zip_file")"

          

      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Extract ZIP file contents" || echo "No changes to commit"
          git push
